name: Vint
on: [push, pull_request]
jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup dependencies
      run: pip install vim-vint
    - name: Run Vimscript Linter
      run: vint .
